@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaskHubParser" as TaskHubParser LOGIC_COLOR
participant ":DeleteEmployeeCommandParser" as DeleteEmployeeCommandParser LOGIC_COLOR
participant "d:DeleteEmployeeCommand" as DeleteEmployeeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deleteE 1")
activate LogicManager

LogicManager -> TaskHubParser : parseCommand("deleteE 1")
activate TaskHubParser

create DeleteEmployeeCommandParser
TaskHubParser -> DeleteEmployeeCommandParser
activate DeleteEmployeeCommandParser

DeleteEmployeeCommandParser --> TaskHubParser
deactivate DeleteEmployeeCommandParser

TaskHubParser -> DeleteEmployeeCommandParser : parse("1")
activate DeleteEmployeeCommandParser

create DeleteEmployeeCommand
DeleteEmployeeCommandParser -> DeleteEmployeeCommand
activate DeleteEmployeeCommand

DeleteEmployeeCommand --> DeleteEmployeeCommandParser : d
deactivate DeleteEmployeeCommand

DeleteEmployeeCommandParser --> TaskHubParser : d
deactivate DeleteEmployeeCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteEmployeeCommandParser -[hidden]-> TaskHubParser
destroy DeleteEmployeeCommandParser

TaskHubParser --> LogicManager : d
deactivate TaskHubParser

LogicManager -> DeleteEmployeeCommand : execute()
activate DeleteEmployeeCommand

DeleteEmployeeCommand -> Model : deleteEmployee(1)
activate Model

Model --> DeleteEmployeeCommand
deactivate Model

create CommandResult
DeleteEmployeeCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteEmployeeCommand
deactivate CommandResult

DeleteEmployeeCommand --> LogicManager : result
deactivate DeleteEmployeeCommand

[<--LogicManager
deactivate LogicManager
@enduml
